stages:
  - push

sync_to_github:
  stage: push
  script:
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/bolt2000/repository.git || true
    - git push --force github main
  only:
    - main
